import Head from "next/head"

const Settings = () => {
    return (
        <div>
        <Head>
          <title>Air OS | Settings</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <div>Welcome to Settings!</div>
        
        </div>
    )
}

export default Settings